name: Build and Test

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false # we have an i18n app and need to turn it on
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: '1' # Enable color output, even though the console output is redirected in Actions
  TERM: xterm # Enable color output in GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build and Test
    services:
      rabbitmq:
        image: rabbitmq:3.8-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        # needed because the rabbitmq container does not provide a healthcheck
        options: >-
          --health-cmd "rabbitmqctl node_health_check" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v4
      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
      - name: Install Dependencies
        run: |
          dotnet restore ./RabbitMqManagement.sln
      - name: Build
        run: |
          dotnet build ./RabbitMqManagement.sln -c Release --no-restore
      - name: Tests
        run: dotnet test ./RabbitMqManagement.sln -c Release --no-restore
